### ISSUE TITLE
How can I install stable version-1.1.1

### ISSUE THREAD

**Issue by cyongxue** [wgliang/goreporter#10]
➜  GoglandProjects go get -u github.com/wgliang/goreporter/tree/version-1.1.1
package github.com/wgliang/goreporter/tree/version-1.1.1: cannot find package "github.com/wgliang/goreporter/tree/version-1.1.1" in any of:
	/usr/local/go/src/github.com/wgliang/goreporter/tree/version-1.1.1 (from $GOROOT)
	/Users/yongxue/GoglandProjects/src/github.com/wgliang/goreporter/tree/version-1.1.1 (from $GOPATH)

**Comment by wgliang** [comment]
see https://github.com/wgliang/goreporter/releases

**Comment by jeff-knurek** [comment]
try using a 3rd party tool like glide - I don't think the suggestion in the README works (or at least not for me in go 1.8)
