### ISSUE TITLE
runtime error: slice bounds out of range

### ISSUE THREAD

**Issue by cyongxue** [wgliang/goreporter#12]
[Apollo]2017/04/13 15:01:22 checked spell error
panic: runtime error: slice bounds out of range

goroutine 23 [running]:
panic(0x4b5fc0, 0xc420014100)
	/usr/local/go/src/runtime/panic.go:500 +0x1a1
main.PackageAbsPathExceptSuffix(0xc42000c034, 0x27, 0x537d8a, 0x1)
	/Users/yongxue/GoglandProjects/src/github.com/wgliang/goreporter/utils.go:87 +0x14d
main.(*Reporter).Engine.func5(0x7fff5fbff986, 0x1, 0xc4201900c0, 0xc42011f340)
	/Users/yongxue/GoglandProjects/src/github.com/wgliang/goreporter/engine.go:180 +0x126
created by main.(*Reporter).Engine
	/Users/yongxue/GoglandProjects/src/github.com/wgliang/goreporter/engine.go:185 +0x6ec

**Comment by wgliang** [comment]
Thanks very much.
