### ISSUE TITLE
add goimports (or gofmt)

### ISSUE THREAD

**Issue by jeff-knurek** [wgliang/goreporter#13]
another analysis tool that should be added:
`goimports -d`
https://godoc.org/golang.org/x/tools/cmd/goimports

-------
`gofmt` provides similar output, but maybe not as good http://goinbigdata.com/goimports-vs-gofmt/

**Comment by wgliang** [comment]
The vast majority of the editor will format the code, this is not goreporter focus.

**Comment by jeff-knurek** [comment]
the majority of editors will also lint the code and/or do other static analysis...

my perspective is that if the developer hasn't configured their editor correctly (because that still needs to manually be done, `goimports` doesn't come automatic), these results can be included as one of the points of data that get evaluated during a pull request

**Comment by jeff-knurek** [comment]
"A Golang tool that does static analysis, unit testing, code review and generate code quality report" 
code formatting does in fact sound like the focus of this tool

**Comment by wgliang** [comment]
Thank you very much,I will consider adding this feature to it in the future. If you are willing to work with me to develop goreporter, that would be better.
