### ISSUE TITLE
Can't exclude linters/spellcheck and vendor

### ISSUE THREAD

**Issue by derekstavis** [wgliang/goreporter#19]
Looks like `-e` flag isn't working with `linters/spellcheck`.

When running `goreporter` on our project the following way:

```sh
$ goreporter -e vendor,linters/spellcheck -f json -p ../thunderbolt 
``` 

SpellCheck isn't being ignored. When running ignoring only vendor:

```sh
$ goreporter -e vendor -f json -p ../thunderbolt 
``` 

It looks like every linter is ignoring vendor, but SpellCheck isn't.

#### Evidences:

```json
...
        "compress": {
          "name": "github.com/pagarme/thunderbolt/vendor/github.com/klauspost/compress",
          "description": "",
          "errors": [
            {
              "line_number": 23,
              "error_string": "/home/derek/go/src/github.com/pagarme/thunderbolt/vendor/github.com/klauspost/compress/README.md:23:141: \"progresssion\" is a misspelling of \"progressions\""
            },
            {
              "line_number": 200,
              "error_string": "/home/derek/go/src/github.com/pagarme/thunderbolt/vendor/github.com/klauspost/compress/README.md:200:121: \"descibed\" is a misspelling of \"described\""
            }
          ]
        },
...
```

####

**Comment by wgliang** [comment]
Yes, I understand your issue. SpellCheck is about to join linter, but I have not figured out how the page is displayed. This problem I will try to fix it as soon as possible. Thx!

**Comment by wgliang** [comment]
Now,you can pull last update and run goreporter on your project.Any questions can contact me. Thank you for issue.

**Comment by wgliang** [comment]
Did I solve your problem? I want to close the issue if you are ok. 
@derekstavis

**Comment by derekstavis** [comment]
Hey @wgliang, it solved my issue!! Thanks a lot for your time!!!
