### ISSUE TITLE
Exclude vendor from tests ?

### ISSUE THREAD

**Issue by alexjomin** [wgliang/goreporter#2]
Hello,

I was actually looking for a tool to generate a code quality report on our PRs, it seems to fit to my needs ! Thank you

But Is there a way not to test the `vendor` folder ?

**Comment by wgliang** [comment]
Thank you for loving it.
Vendor which is mostly open source library, and our code review is more focused on our project we developed the code.

**Comment by jeff-knurek** [comment]
excluding `vendor` seems like it'd be a good default, but for now I've gone with using the `-e` flag

**Comment by kisPocok** [comment]
Could you open this issue again? I think, It would be nice to have a "disable vendor check" flag.
