### ISSUE TITLE
More linters

### ISSUE THREAD

**Issue by udhos** [wgliang/goreporter#3]
Find more linters here:
https://github.com/alecthomas/gometalinter

**Comment by wgliang** [comment]
Thank you, I will continue to work, but also welcome with me to improve it.

**Comment by matrixik** [comment]
udhos probably mean that you could probably implement gometalinter support that already group and normalize output from many other linters instead of implementing them all one by one.

**Comment by wgliang** [comment]
I understand what you mean, and I've ever thought about doing that. 

But there are two reasons:
1. Each linters author will often change its interface and implementation
2. Some linters do not meet the requirements of goreporter and need to make changes

So I import a number of linters and transformed them.
