### ISSUE TITLE
Slice bounds out of range when using ./

### ISSUE THREAD

**Issue by nkovacs** [wgliang/goreporter#6]
If I use `./`, like this:

```
goreporter -p ./ -d ./goreporter -r html -t ../../github.com/wgliang/goreporter/templates/template.html
```

```
panic: runtime error: slice bounds out of range

goroutine 1 [running]:
main.DirList.func1(0xc4202261f8, 0x7, 0xccff80, 0xc42022b2b0, 0x0, 0x0, 0x0, 0x0)
        /home/nkovacs/progs/go/src/github.com/wgliang/goreporter/utils.go:24 +0x219
path/filepath.walk(0xc4202261f8, 0x7, 0xccff80, 0xc42022b2b0, 0xc420385b00, 0x0, 0x0)
        /usr/local/go/src/path/filepath/path.go:351 +0x81
path/filepath.walk(0x7ffc150c417f, 0x2, 0xccff80, 0xc420380270, 0xc420385b00, 0x0, 0x30)
        /usr/local/go/src/path/filepath/path.go:376 +0x414
path/filepath.Walk(0x7ffc150c417f, 0x2, 0xc420385b00, 0xc4203801a0, 0x0)
        /usr/local/go/src/path/filepath/path.go:398 +0x14c
main.DirList(0x7ffc150c417f, 0x2, 0x97057b, 0x3, 0x0, 0x0, 0xc4200fab70, 0x0, 0x0)
        /home/nkovacs/progs/go/src/github.com/wgliang/goreporter/utils.go:32 +0x16a
main.(*Reporter).Engine(0xc4200b6240, 0x7ffc150c417f, 0x2, 0x0, 0x0)
        /home/nkovacs/progs/go/src/github.com/wgliang/goreporter/engine.go:130 +0x300
main.main()
        /home/nkovacs/progs/go/src/github.com/wgliang/goreporter/main.go:73 +0x2e8
```

If I cd into the goreporter directory, and use `../`, it works.

**Comment by nkovacs** [comment]
Unfortunately, now all my unit tests fail.
When I try to run go test with an absolute path, it says "cannot import absolute path".

**Comment by wgliang** [comment]
yes,I am fixing the problem.

**Comment by wgliang** [comment]
Considering a variety of situations where the project is set to the current path (./) or the upper layer(../), I did not expect an elegant way to accommodate this situation, so I would force -p to set the relative path at the end of the project name.

Do you have a better solution?

**Comment by nkovacs** [comment]
The issue is that `filepath.Walk` calls `filepath.Join`, which calls `filepath.Clean`, and that removes the leading "./", because it's not usually needed. However, go test needs the leading "./", because otherwise it interprets the argument as a package name (relative to "$GOPATH/src").

So the solution is to handle `unittest.UnitTest` appropriately. If `DirList` is guaranteed to return relative paths, then just prepending `"." + filepath.Separator` to the path before calling `unittest.UnitTest` fixes the issue (only tested on Linux, I think "." works on Windows too).

It seems only unittest has this issue, because it executes `go test`. The other linters stay in go code, and therefore they all handle the path correctly ("somedir" == "./somedir").

Also, what is the purpose of the variable called `system` (that's a confusing name). Why not just use filepath.Separator?

**Comment by nkovacs** [comment]
I've pushed a quick and dirty fix that works for me on Linux with `-p ./` and `-p ../`.
