### ISSUE TITLE
The template path is not specified

### ISSUE THREAD

**Issue by MichaelHipp** [wgliang/goreporter#8]
Using HEAD...

`goreporter -p ./myproject` gives
 `[Apollo]2017/04/11 14:18:39 The template path is not specified`

The README.md indicates specifying the template file is optional. I don't have a template file and would prefer it just supply me with a default template file for now. Thanks.

**Comment by wgliang** [comment]
Template in the github.com/wgliang/goreporter/templates/template.html.

**Comment by MichaelHipp** [comment]
Thanks. But the README indicates it's optional, which is evidently not correct. And it would be nice if it would default to that one if none is specified.

**Comment by wgliang** [comment]
{-t templatePathIfHtml} means if you want a html you must specify it.

Thank you for your suggestion, I will reconsider the current method

**Comment by MichaelHipp** [comment]
> {-t templatePathIfHtml} means if you want a html you must specify it.

Not sure I understand. If I don't specify it, it just fails with an error (see above).

**Comment by wgliang** [comment]
you can run it:

**Comment by wgliang** [comment]
you can run it:

./goreporter -p ../goreporter -r html -t ./templates/template.html OR ./goreporter -p ../goreporter -t ./templates/template.html

**Comment by wgliang** [comment]
Thank you for your suggestion,and it will default to that one if none is specified.

**Comment by cyongxue** [comment]
How can I install stable version-1.1.1


➜ GoglandProjects go get -u github.com/wgliang/goreporter/tree/version-1.1.1
package github.com/wgliang/goreporter/tree/version-1.1.1: cannot find package "github.com/wgliang/goreporter/tree/version-1.1.1" in any of:
/usr/local/go/src/github.com/wgliang/goreporter/tree/version-1.1.1 (from $GOROOT)
/Users/yongxue/GoglandProjects/src/github.com/wgliang/goreporter/tree/version-1.1.1 (from $GOPATH)




原始邮件
发件人:wangguoliangnotifications@github.com
收件人:wgliang/goreportergoreporter@noreply.github.com
抄送:Subscribedsubscribed@noreply.github.com
发送时间:2017年4月12日(周三) 10:51
主题:Re: [wgliang/goreporter] The template path is not specified (#8)


Thank you for your suggestion,and it will default to that one if none is specified.

**Comment by jeff-knurek** [comment]
@wgliang I think you're missing the point of the comment:
```
goreporter -p undertest -r json
[Apollo]2017/04/12 14:03:44 The template path is not specified,and will use the default template[./templates/template.html]
[Apollo]2017/04/12 14:03:44 open ./templates/template.html: no such file or directory
```
is the same error as 
```
goreporter -p undertest -r html
[Apollo]2017/04/12 14:05:26 The template path is not specified,and will use the default template[./templates/template.html]
[Apollo]2017/04/12 14:05:26 open ./templates/template.html: no such file or directory
```

I tried using `-t /go/src/github.com/wgliang/goreporter/templates/template.html`, but it fails when generating the output in html:
```
html/template:skylar-apollo: ends in a non-text context: {stateCSS delimNone urlPartNone jsCtxRegexp attrNone elementStyle <nil>}
```

What I would like is some documentation on what this template file is suppose to include. And more examples than the existing broken one.

**Comment by MichaelHipp** [comment]
I updated to latest and am now getting the same error.

`$ goreporter -p ./shopalarm
[Apollo]2017/04/12 10:29:03 The template path is not specified,and will use the default template[./templates/template.html]
[Apollo]2017/04/12 10:29:03 open ./templates/template.html: The system cannot find the path specified.`

It seems to want _me_ to know where to find its magic template file.

**Comment by wgliang** [comment]
Can not find the template file. The template file in github.com/wgliang/goreporter/template/template.html.

Now,unless you specify a valid template, otherwise it will use the default template file, I have written into the program, you can safely try again.

Thank you very much for your attention and pointing out my mistakes.

**Comment by jeff-knurek** [comment]
working for me now, thanks

**Comment by wgliang** [comment]
@jeff-knurek This problem has also been fixed due to the previous increase in style errors. 
See in  [fix style](https://github.com/wgliang/goreporter/commit/1a15b456f55ef2e6b9091cd43f668e4f680bdb2a#diff-2e3fb8d2c70b58a537c8e41659d99d46)
